# 要約モデルの作成

### データの読み込み

In [1]:
import pandas as pd

# エラー行をスキップして読み込む(on_bad_linesで不正レコードを警告なしでスキップされる)
df = pd.read_csv('output.tsv', sep='\t', on_bad_lines='skip', encoding='utf-8')

# 確認
df

,要約1,要約2,要約3,本文
0,岡むら屋から、期間限定の新メニュー「じゃが肉めし」が登場する,男爵いもなどは味噌ベースで煮こまれ、しっかり味が染み込んでいるとのこと,「岡むら屋特製肉じゃが」と言うべき一品に、仕上がっているという,新橋と秋葉原に店を構える「岡むら屋」。味噌ベースの独自の味つけで牛バラ肉を煮込んだ具材がたっ...
1,東京駅周辺の安くて美味しい「蕎麦ランチ」の名店を紹介している,「越後そば 東京店」では、ミニかき揚げ丼セットがおすすめと筆者,その他には、「手打ちそば 石月」「酢重正之 楽」「鎌倉 一茶庵 丸山」など,名店がひしめく「丸の内・日本橋」エリアで＜うまい蕎麦ランチ＞が食べられるお店を厳選してご紹介...
2,8日から「サンクトガーレン」は、「チョコビール」4種を販売する,ダークな茶色、ほろ苦いビターチョコのような香りが特長のビール,毎年バレンタインシーズン限定で販売され、2016年で11年目となるそう,地ビールメーカー「サンクトガーレン」は、「チョコビール」4種を2016年1月8日から全国の取...
3,1年以内に登場した、東京みやげの新定番を紹介している,カファレルの「東京ジャンドゥーヤチョコパイ」,オーボンヴュータンの「ソーシソン・セック」など,何かと人に会う機会が多いこの時期。そんな時、頭を悩ませるのが手みやげ選びだ。毎年似たようなも...
4,ロッテリアが2月15日から「エビバーガー」をリニューアルして販売する,エビにバナメイ種を採用し、衣も粗めに挽くことで具材の味を引き立たせる,また同日より期間限定で「桜えびタルタルのエビバーガー」の販売も開始する,ロッテリア は、現在販売している「エビバーガー」(単品360円)を2月15日(月)からバージ...
...,...,...,...,...
7019,中国メディアが、日本在住の中国人女性による手記を掲載した,「子どもをつれて旅行するなら、やはり日本を選ぶ」と女性,「不測の事態が起きることもなく安心だから」と述べている,日本には数多くの外国人が住んでいるが、こうした外国人の目に映る日本の姿とはいったいどのような...
7020,中国で電気炊飯器をめぐる動きが加速していると報じられた,中国人旅行客が日本で電気炊飯器を爆買いしたことがきっかけだという,スマホメーカーが開発に乗り出し、政府が品質向上を要求しているとのこと,大阪の老舗食堂で５０年以上にわたって、おいしいご飯を炊き続ける村嶋孟（つとむ）さんは、地元で...
7021,中国メディアは、中国高速鉄道の建設に関する難題についての記事を掲載した,鉄道を台湾まで延伸させるには、台湾の民意や安全保障の点が課題だと指摘,「こればかりは中国だけの対応でどうにかなるものではない」と論じている,中国 が２０１６年から２０年までを対象計画とする第１３次５カ年計画に「大陸と 台湾 を結ぶ ...
7022,中国のある企業が熊本地震を祝うセールを実施するとSNSで表明した,ネットでは「歴史問題と地震を一緒にするな」「恥さらしめ」と批判が殺到,騒ぎが大きくなることを恐れたのか、同アカウントは投稿を削除している,地震 の影響で、九州地方はなお予断を許さない状況が続いているが、そうした中、 中国 のとある...
7023,スペインのマットレスメーカーが開発した「Smarttress」を紹介している,マットレスの中のセンサーが不在中のベッド利用を感知し、スマホに通知,ただし本当にこのマットレスが存在するということは確認できていないと筆者,by Lindsay Attaway スペインのマットレスメーカー・Durmetが、夜にはリ...

In [2]:
# 欠損値を削除
df = df.dropna()
df.describe()

,要約1,要約2,要約3,本文
count,7023,7023,7023,7023
unique,7009,7020,7020,7021
top,行方不明だった埼玉県朝霞市の中学生が保護され、男の身柄が確保された事件,コートの中をブラックでまとめると、全体的に引き締まった印象になる,オフタートルニットを合わせるとスタイルアップが図れる,新年が明けると、気分はすっかり春モード。 ファッション も春先の トレンド が気になってくる...
freq,3,3,3,2

**memo**
- データ数を揃えることができた
- 異なるニュース記事でも同じ要約をしているものがある

### 三行の要約文を一行に統合させるデータフレームを追加

In [3]:
df['要約'] = ("<S1>" + df['要約1'] + "<S2>" + df['要約2'] + "<S3>" + df['要約3'])

C:\Users\22t312\AppData\Local\Temp\ipykernel_8332\1033240097.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['要約'] = ("<S1>" + df['要約1'] + "<S2>" + df['要約2'] + "<S3>" + df['要約3'])

**memo**
- 要約文に含まれない特殊トークンを文末に入れることで各要約文を統合して学習した後にまた三行の要約に分割できるようにする
- 今回は要約1に'<S1>', 要約2に'<S2>', 要約3に'<S3>'を加える

In [4]:
print(df['要約'])

0       <S1>岡むら屋から、期間限定の新メニュー「じゃが肉めし」が登場する<S2>男爵いもなどは味...
1       <S1>東京駅周辺の安くて美味しい「蕎麦ランチ」の名店を紹介している<S2>「越後そば 東京...
2       <S1>8日から「サンクトガーレン」は、「チョコビール」4種を販売する<S2>ダークな茶色、...
3       <S1>1年以内に登場した、東京みやげの新定番を紹介している<S2>カファレルの「東京ジャン...
4       <S1>ロッテリアが2月15日から「エビバーガー」をリニューアルして販売する<S2>エビにバ...
                              ...
7019    <S1>中国メディアが、日本在住の中国人女性による手記を掲載した<S2>「子どもをつれて旅行...
7020    <S1>中国で電気炊飯器をめぐる動きが加速していると報じられた<S2>中国人旅行客が日本で電...
7021    <S1>中国メディアは、中国高速鉄道の建設に関する難題についての記事を掲載した<S2>鉄道を...
7022    <S1>中国のある企業が熊本地震を祝うセールを実施するとSNSで表明した<S2>ネットでは「...
7023    <S1>スペインのマットレスメーカーが開発した「Smarttress」を紹介している<S2>...
Name: 要約, Length: 7023, dtype: object

In [5]:
row = df[df['要約'].str.contains('<S3>')]
print(row)

                                         要約1  \
0             岡むら屋から、期間限定の新メニュー「じゃが肉めし」が登場する
1             東京駅周辺の安くて美味しい「蕎麦ランチ」の名店を紹介している
2            8日から「サンクトガーレン」は、「チョコビール」4種を販売する
3                 1年以内に登場した、東京みやげの新定番を紹介している
4         ロッテリアが2月15日から「エビバーガー」をリニューアルして販売する
...                                      ...
7019            中国メディアが、日本在住の中国人女性による手記を掲載した
7020             中国で電気炊飯器をめぐる動きが加速していると報じられた
7021     中国メディアは、中国高速鉄道の建設に関する難題についての記事を掲載した
7022        中国のある企業が熊本地震を祝うセールを実施するとSNSで表明した
7023  スペインのマットレスメーカーが開発した「Smarttress」を紹介している

                                      要約2  \
0     男爵いもなどは味噌ベースで煮こまれ、しっかり味が染み込んでいるとのこと
1         「越後そば 東京店」では、ミニかき揚げ丼セットがおすすめと筆者
2          ダークな茶色、ほろ苦いビターチョコのような香りが特長のビール
3                  カファレルの「東京ジャンドゥーヤチョコパイ」
4      エビにバナメイ種を採用し、衣も粗めに挽くことで具材の味を引き立たせる
...                                   ...
7019          「子どもをつれて旅行するなら、やはり日本を選ぶ」と女性
7020     中国人旅行客が日本で電気炊飯器を爆買いしたことがきっかけだという
7021   鉄道を台湾まで延伸させるには、台湾の民意や安全保障の点が課題だと指摘
7022   ネットでは「歴史問題と地震を一緒にするな」「恥さらしめ」と批判が殺到
7023    マットレスの中のセンサーが不在中のベッド利用を感知し、スマホに通知

                                        要約3  \
0           「岡むら屋特製肉じゃが」と言うべき一品に、仕上がっているという
1     その他には、「手打ちそば 石月」「酢重正之 楽」「鎌倉 一茶庵 丸山」など
2       毎年バレンタインシーズン限定で販売され、2016年で11年目となるそう
3                   オーボンヴュータンの「ソーシソン・セック」など
4       また同日より期間限定で「桜えびタルタルのエビバーガー」の販売も開始する
...                                     ...
7019            「不測の事態が起きることもなく安心だから」と述べている
7020     スマホメーカーが開発に乗り出し、政府が品質向上を要求しているとのこと
7021     「こればかりは中国だけの対応でどうにかなるものではない」と論じている
7022      騒ぎが大きくなることを恐れたのか、同アカウントは投稿を削除している
7023    ただし本当にこのマットレスが存在するということは確認できていないと筆者

                                                     本文  \
0     新橋と秋葉原に店を構える「岡むら屋」。味噌ベースの独自の味つけで牛バラ肉を煮込んだ具材がたっ...
1     名店がひしめく「丸の内・日本橋」エリアで＜うまい蕎麦ランチ＞が食べられるお店を厳選してご紹介...
2     地ビールメーカー「サンクトガーレン」は、「チョコビール」4種を2016年1月8日から全国の取...
3     何かと人に会う機会が多いこの時期。そんな時、頭を悩ませるのが手みやげ選びだ。毎年似たようなも...
4     ロッテリア は、現在販売している「エビバーガー」(単品360円)を2月15日(月)からバージ...
...                                                 ...
7019  日本には数多くの外国人が住んでいるが、こうした外国人の目に映る日本の姿とはいったいどのような...
7020  大阪の老舗食堂で５０年以上にわたって、おいしいご飯を炊き続ける村嶋孟（つとむ）さんは、地元で...
7021  中国 が２０１６年から２０年までを対象計画とする第１３次５カ年計画に「大陸と 台湾 を結ぶ ...
7022  地震 の影響で、九州地方はなお予断を許さない状況が続いているが、そうした中、 中国 のとある...
7023  by Lindsay Attaway スペインのマットレスメーカー・Durmetが、夜にはリ...

                                                     要約
0     <S1>岡むら屋から、期間限定の新メニュー「じゃが肉めし」が登場する<S2>男爵いもなどは味...
1     <S1>東京駅周辺の安くて美味しい「蕎麦ランチ」の名店を紹介している<S2>「越後そば 東京...
2     <S1>8日から「サンクトガーレン」は、「チョコビール」4種を販売する<S2>ダークな茶色、...
3     <S1>1年以内に登場した、東京みやげの新定番を紹介している<S2>カファレルの「東京ジャン...
4     <S1>ロッテリアが2月15日から「エビバーガー」をリニューアルして販売する<S2>エビにバ...
...                                                 ...
7019  <S1>中国メディアが、日本在住の中国人女性による手記を掲載した<S2>「子どもをつれて旅行...
7020  <S1>中国で電気炊飯器をめぐる動きが加速していると報じられた<S2>中国人旅行客が日本で電...
7021  <S1>中国メディアは、中国高速鉄道の建設に関する難題についての記事を掲載した<S2>鉄道を...
7022  <S1>中国のある企業が熊本地震を祝うセールを実施するとSNSで表明した<S2>ネットでは「...
7023  <S1>スペインのマットレスメーカーが開発した「Smarttress」を紹介している<S2>...

[7023 rows x 5 columns]

**memo**
- すべての要素に特殊トークンが存在している

### 変更したdf(一行に統合した要約を追加)をoutput.csvに保存

In [6]:
df.to_csv("output.csv", index=False, encoding='utf-8-sig')

### 学習

### 授業で習ったようにシャッフルスピリットでデータを分割

In [2]:
import numpy as np

X = np.array(df['本文'])
y = np.array(df['要約'])

from sklearn.model_selection import KFold
# 5-fold CV
ss = KFold(n_splits=5, shuffle=True, random_state=0)

for train_index, test_index in ss.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

**memo**
- 自然言語処理では文字列データのためNumpy配列では動作が遅くなってしまうらしい？

**memo**
- PyTorchとTensowflowを両方インストールしていると競合してしまい、エラーが表示される場合があるため新たな仮想環境を作成し、Pytorchのみインストールしている環境を作成する

### ライブラリの競合が起こったため、仮想環境を作成

In [1]:
!python -m venv pytorch

In [3]:
# 仮想環境の有効化とパッケージのインストール
!pytorch\Scripts\activate && pip install --upgrade pip
!pytorch\Scripts\activate && pip install torch transformers accelerate ipykernel

Requirement already satisfied: pip in c:\users\22t312\desktop\csss実験システム発表\ライブドア要約モデル\pytorch\lib\site-packages (22.3.1)
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)

ERROR: To modify pip, please run the following command:
C:\Users\22t312\Desktop\CSSS実験システム発表\ライブドア要約モデル\pytorch\Scripts\python.exe -m pip install --upgrade pip

[notice] A new release of pip available: 22.3.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting torch
  Downloading torch-2.5.1-cp311-cp311-win_amd64.whl (203.1 MB)
     -------------------------------------- 203.1/203.1 MB 3.1 MB/s eta 0:00:00
Collecting transformers
  Downloading transformers-4.48.0-py3-none-any.whl (9.7 MB)
     ---------------------------------------- 9.7/9.7 MB 14.4 MB/s eta 0:00:00
Collecting accelerate
  Downloading accelerate-1.2.1-py3-none-any.whl (336 kB)
     ------------------------------------- 336.4/336.4 kB 20.4 MB/s eta 0:00:00
Collecting ipykernel
  Downloading ipykernel-6.29.5-py3-none-any.whl (117 kB)
     -------------------------------------- 117.2/117.2 kB 7.1 MB/s eta 0:00:00
Collecting filelock
  Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
Collecting typing-extensions>=4.8.0
  Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting networkx
  Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
     ---------------------------------------- 1.7/1.7 MB 6.1 MB/s eta 0:00:00
Collecting jinja2
  Downloading jinja2-3.1.5-py3-none-any.whl (134 kB)
     -------------------------------------- 134.6/134.6 kB 7.8 MB/s eta 0:00:00
Collecting fsspec
  Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
     ---------------------------------------- 183.9/183.9 kB ? eta 0:00:00
Collecting sympy==1.13.1
  Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
     ---------------------------------------- 6.2/6.2 MB 17.2 MB/s eta 0:00:00
Collecting mpmath<1.4,>=1.1.0
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
     ------------------------------------- 536.2/536.2 kB 16.4 MB/s eta 0:00:00
Collecting huggingface-hub<1.0,>=0.24.0
  Downloading huggingface_hub-0.27.1-py3-none-any.whl (450 kB)
     -------------------------------------- 450.7/450.7 kB 3.1 MB/s eta 0:00:00
Collecting numpy>=1.17
  Downloading numpy-2.2.1-cp311-cp311-win_amd64.whl (12.9 MB)
     --------------------------------------- 12.9/12.9 MB 15.2 MB/s eta 0:00:00
Collecting packaging>=20.0
  Downloading packaging-24.2-py3-none-any.whl (65 kB)
     ---------------------------------------- 65.5/65.5 kB ? eta 0:00:00
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0.2-cp311-cp311-win_amd64.whl (161 kB)
     ---------------------------------------- 162.0/162.0 kB ? eta 0:00:00
Collecting regex!=2019.12.17
  Downloading regex-2024.11.6-cp311-cp311-win_amd64.whl (274 kB)
     -------------------------------------- 274.1/274.1 kB 5.6 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.32.3-py3-none-any.whl (64 kB)
     ---------------------------------------- 64.9/64.9 kB 3.4 MB/s eta 0:00:00
Collecting tokenizers<0.22,>=0.21
  Downloading tokenizers-0.21.0-cp39-abi3-win_amd64.whl (2.4 MB)
     ---------------------------------------- 2.4/2.4 MB 13.8 MB/s eta 0:00:00
Collecting safetensors>=0.4.1
  Downloading safetensors-0.5.2-cp38-abi3-win_amd64.whl (303 kB)
     -------------------------------------- 303.8/303.8 kB 1.7 MB/s eta 0:00:00
Collecting tqdm>=4.27
  Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
     ---------------------------------------- 78.5/78.5 kB ? eta 0:00:00
Collecting psutil
  Downloading psutil-6.1.1-cp37-abi3-win_amd64.whl (254 kB)
     -------------------------------------- 254.4/254.4 kB 7.9 MB/s eta 0:00:00
Collecting comm>=0.1.1
  Downloading comm-0.2.2-py3-none-any.whl (7.2 kB)
Collecting debugpy>=1.6.5
  Downloading debugpy-1.8.11-cp311-cp311-win_amd64.whl (5.1 MB)
     ---------------------------------------- 5.1/5.1 MB 14.9 MB/s eta 0:00:00
Collecting ipython>=7.23.1
  Downloading ipython-8.31.0-py3-none-any.whl (821 kB)
     ------------------------------------- 821.6/821.6 kB 17.6 MB/s eta 0:00:00
Collecting jupyter-client>=6.1.12
  Downloading jupyter_client-8.6.3-py3-none-any.whl (106 kB)
     ---------------------------------------- 106.1/106.1 kB ? eta 0:00:00
Collecting jupyter-core!=5.0.*,>=4.12
  Downloading jupyter_core-5.7.2-py3-none-any.whl (28 kB)
Collecting matplotlib-inline>=0.1
  Downloading matplotlib_inline-0.1.7-py3-none-any.whl (9.9 kB)
Collecting nest-asyncio
  Downloading nest_asyncio-1.6.0-py3-none-any.whl (5.2 kB)
Collecting pyzmq>=24
  Downloading pyzmq-26.2.0-cp311-cp311-win_amd64.whl (642 kB)
     ------------------------------------- 642.3/642.3 kB 42.1 MB/s eta 0:00:00
Collecting tornado>=6.1
  Downloading tornado-6.4.2-cp38-abi3-win_amd64.whl (438 kB)
     ------------------------------------- 438.9/438.9 kB 13.4 MB/s eta 0:00:00
Collecting traitlets>=5.4.0
  Downloading traitlets-5.14.3-py3-none-any.whl (85 kB)
     ---------------------------------------- 85.4/85.4 kB ? eta 0:00:00
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jedi>=0.16
  Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
     ---------------------------------------- 1.6/1.6 MB 12.5 MB/s eta 0:00:00
Collecting prompt_toolkit<3.1.0,>=3.0.41
  Downloading prompt_toolkit-3.0.48-py3-none-any.whl (386 kB)
     ------------------------------------- 386.6/386.6 kB 12.1 MB/s eta 0:00:00
Collecting pygments>=2.4.0
  Downloading pygments-2.19.1-py3-none-any.whl (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 19.6 MB/s eta 0:00:00
Collecting stack_data
  Using cached stack_data-0.6.3-py3-none-any.whl (24 kB)
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     ------------------------------------- 229.9/229.9 kB 13.7 MB/s eta 0:00:00
Collecting platformdirs>=2.5
  Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
Collecting pywin32>=300
  Downloading pywin32-308-cp311-cp311-win_amd64.whl (6.6 MB)
     ---------------------------------------- 6.6/6.6 MB 17.5 MB/s eta 0:00:00
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-3.0.2-cp311-cp311-win_amd64.whl (15 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.4.1-cp311-cp311-win_amd64.whl (102 kB)
     -------------------------------------- 102.4/102.4 kB 5.8 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.10-py3-none-any.whl (70 kB)
     ---------------------------------------- 70.4/70.4 kB 3.8 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.3.0-py3-none-any.whl (128 kB)
     -------------------------------------- 128.4/128.4 kB 7.4 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2024.12.14-py3-none-any.whl (164 kB)
     -------------------------------------- 164.9/164.9 kB 5.0 MB/s eta 0:00:00
Collecting parso<0.9.0,>=0.8.4
  Downloading parso-0.8.4-py2.py3-none-any.whl (103 kB)
     -------------------------------------- 103.7/103.7 kB 6.2 MB/s eta 0:00:00
Collecting wcwidth
  Downloading wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Collecting six>=1.5
  Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Collecting executing>=1.2.0
  Downloading executing-2.1.0-py2.py3-none-any.whl (25 kB)
Collecting asttokens>=2.1.0
  Downloading asttokens-3.0.0-py3-none-any.whl (26 kB)
Collecting pure-eval
  Downloading pure_eval-0.2.3-py3-none-any.whl (11 kB)
Installing collected packages: wcwidth, pywin32, pure-eval, mpmath, urllib3, typing-extensions, traitlets, tornado, sympy, six, safetensors, regex, pyzmq, pyyaml, pygments, psutil, prompt_toolkit, platformdirs, parso, packaging, numpy, networkx, nest-asyncio, MarkupSafe, idna, fsspec, filelock, executing, decorator, debugpy, colorama, charset-normalizer, certifi, asttokens, tqdm, stack_data, requests, python-dateutil, matplotlib-inline, jupyter-core, jinja2, jedi, comm, torch, jupyter-client, ipython, huggingface-hub, tokenizers, ipykernel, accelerate, transformers
Successfully installed MarkupSafe-3.0.2 accelerate-1.2.1 asttokens-3.0.0 certifi-2024.12.14 charset-normalizer-3.4.1 colorama-0.4.6 comm-0.2.2 debugpy-1.8.11 decorator-5.1.1 executing-2.1.0 filelock-3.16.1 fsspec-2024.12.0 huggingface-hub-0.27.1 idna-3.10 ipykernel-6.29.5 ipython-8.31.0 jedi-0.19.2 jinja2-3.1.5 jupyter-client-8.6.3 jupyter-core-5.7.2 matplotlib-inline-0.1.7 mpmath-1.3.0 nest-asyncio-1.6.0 networkx-3.4.2 numpy-2.2.1 packaging-24.2 parso-0.8.4 platformdirs-4.3.6 prompt_toolkit-3.0.48 psutil-6.1.1 pure-eval-0.2.3 pygments-2.19.1 python-dateutil-2.9.0.post0 pywin32-308 pyyaml-6.0.2 pyzmq-26.2.0 regex-2024.11.6 requests-2.32.3 safetensors-0.5.2 six-1.17.0 stack_data-0.6.3 sympy-1.13.1 tokenizers-0.21.0 torch-2.5.1 tornado-6.4.2 tqdm-4.67.1 traitlets-5.14.3 transformers-4.48.0 typing-extensions-4.12.2 urllib3-2.3.0 wcwidth-0.2.13

[notice] A new release of pip available: 22.3.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
!pytorch\Scripts\activate && python -m ipykernel install --user --name=pytorch --display-name "Python (pytorch)"

Installed kernelspec pytorch in C:\Users\22t312\AppData\Roaming\jupyter\kernels\pytorch

### 学習データ:テストデータ=8:2のHold-outで実施

In [1]:
from sklearn.model_selection import ShuffleSplit
import pandas as pd
import numpy as np

# データの読み込み
df = pd.read_csv("output.csv")  # CSVファイルを読み込む
X = np.array(df['本文'])
y = np.array(df['要約'])

ss = ShuffleSplit(n_splits=1, 
                  train_size=0.8,
                  test_size=0.2, 
                  random_state=3)

train_index, test_index = next(ss.split(X))
X_train, X_test = X[train_index], X[test_index]
y_train, y_test = y[train_index], y[test_index]

In [2]:
print(f"all: {np.unique(y, return_counts=True)[1] / y.size} {y.size}")
print(f"train: {np.unique(y_train, return_counts=True)[1] / y_train.size} {y_train.size}")
print(f"test: {np.unique(y_test, return_counts=True)[1] / y_test.size} {y_test.size}")

all: [0.00014239 0.00014239 0.00014239 ... 0.00014239 0.00014239 0.00014239] 7023
train: [0.000178 0.000178 0.000178 ... 0.000178 0.000178 0.000178] 5618
test: [0.00071174 0.00071174 0.00071174 ... 0.00071174 0.00071174 0.00071174] 1405

**memo**
- 学習データ:テストデータ=8:2になってる

In [2]:
X_train, X_test = list(X_train), list(X_test)
y_train, y_test = list(y_train), list(y_test)

**memo**
- トークナイズの関係でデータをリストとする必要がある

### トークナイズ(前処理)　文字　→　数値

In [5]:
from transformers import T5Tokenizer

# 日本語モデルをロード
tokenizer = T5Tokenizer.from_pretrained('sonoisa/t5-base-japanese')

# トークナイズ関数
def preprocess_data(texts, summaries, tokenizer):
    # T5形式に変換
    inputs = []
    for text in texts:
        # T5は様々なタスクに使用されるためsummarize(要約)と明記しておいた方が良い
        inputs.append("summarize: " + str(text))

    model_inputs = tokenizer(
        inputs, max_length=512, truncation=True, padding="max_length"
    )
    labels = tokenizer(
        summaries, max_length=128, truncation=True, padding="max_length"
    )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

# トレーニングデータをトークナイズ
train_data = preprocess_data(X_train, y_train, tokenizer)
# テストデータをトークナイズ
test_data = preprocess_data(X_test, y_test, tokenizer)

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

### PyTorchのデータセットクラスを作成し学習データとテストデータを効率よく扱える形式に変換

In [7]:
import torch
from torch.utils.data import Dataset

class NewsSummaryDataset(Dataset):
    def __init__(self, encodings):
        self.encodings = encodings

    def __len__(self):
        return len(self.encodings["input_ids"])

    def __getitem__(self, idx):
        item = {}
        for key, val in self.encodings.items():
            item[key] = torch.tensor(val[idx])

        return item

# PyTorchデータセットの作成
train_dataset = NewsSummaryDataset(train_data)
test_dataset = NewsSummaryDataset(test_data)

**memo**
- 今回使用するtransformersは最新のKerasと対応しておらず、tensowflowと相性が悪い
- 一方でtransformersはPytorchと相性が良い

### モデルの読み込み

In [8]:
from transformers import T5ForConditionalGeneration

# モデルのロード
model = T5ForConditionalGeneration.from_pretrained('sonoisa/t5-base-japanese')

### モデルを学習する際の設定を定義

In [9]:
from transformers import TrainingArguments

# トレーニング引数の設定
training_args = TrainingArguments(
    output_dir="./results",          # モデルの保存先
    eval_strategy="epoch",           # 各エポックで評価
    learning_rate=5e-5,              # 学習率
    per_device_train_batch_size=4,   # バッチサイズ
    per_device_eval_batch_size=4,    # 評価時のバッチサイズ
    num_train_epochs=3,              # エポック数
    weight_decay=0.01,               # 正則化
    logging_dir="./logs",            # ログ保存先
)

### モデル学習の準備

In [10]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)

### 学習の開始

In [11]:
trainer.train()

Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

KeyboardInterrupt:

### jupyter notebookでは学習に非常に時間がかかるためGoogle colaboratoryのGPUを用いて学習を行う

### 要約モデルを用いておためしで要約文を生成

In [17]:
from transformers import T5Tokenizer, T5ForConditionalGeneration
import pandas as pd

# 保存済みモデルのディレクトリ
model_dir = "./results_ver2"
tokenizer = T5Tokenizer.from_pretrained(model_dir)
model = T5ForConditionalGeneration.from_pretrained(model_dir)

# ニュース本文
input_texts = "大みそか恒例、年末ジャンボ宝くじの抽選会が行われ、1等・前後賞合わせて10億円の当選番号が発表されました。今年の年末ジャンボ宝くじは1等の7億円が23本、前後賞の1億5000万円が46本で、1等と前後賞を合わせると10億円が当たります。100万円以上の当せん本数は「年末ジャンボミニ」も含めると合計1万4403本に上ります。▼1等の当選番号は110組の10万6348番、▼2等・1000万円は52組の15万1307番、49組の13万5439番、139組の16万7124番、65組の13万8164番、60組の12万2015番、46組の11万6185番、60組の11万0493番、84組の12万0749番です。▼3等・100万円は各組共通で10万3265番と16万4169番です。当せん金の受け取りは来年1月7日からとなっています。"

# 要約結果を保存するリスト
summaries = []

# 各ニュース本文を処理
for text in input_texts:
    # トークナイズ(モデルが認識できるように文字データを数値データに変換させる)
    inputs = tokenizer(
        "summarize: " + text,
        return_tensors="pt",
        max_length=1024,
        truncation=True
    )

    # 要約生成
    summary_ids = model.generate(
        inputs["input_ids"],
        max_length=128,
        num_beams=4,    # 4つの候補から最適な出力を選択
        early_stopping=True
    )

    # 要約結果を取得
    # 数値データ　→　文字データ
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
    summaries.append(summary)

# 要約結果を DataFrame に追加して保存
print(summaries)

KeyboardInterrupt:

### BERTScoreとRouge値の導出方法を理解する

In [4]:
pip install bert_score

Collecting bert_score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: torch>=1.0.0 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from bert_score) (2.3.1)
Requirement already satisfied: pandas>=1.0.1 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from bert_score) (2.2.0)
Requirement already satisfied: transformers>=3.0.0 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from bert_score) (4.48.0)
Requirement already satisfied: numpy in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from bert_score) (1.26.3)
Requirement already satisfied: requests in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from bert_score) (2.31.0)
Requirement already satisfied: tqdm>=4.31.1 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from bert_score) (4.66.4)
Requirement already satisfied: matplotlib in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from bert_score) (3.9.0)
Requirement already satisfied: packaging>=20.9 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from bert_score) (23.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.1->bert_score) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.1->bert_score) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.1->bert_score) (2023.4)
Requirement already satisfied: filelock in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.0.0->bert_score) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.0.0->bert_score) (4.12.2)
Requirement already satisfied: sympy in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.0.0->bert_score) (1.12.1)
Requirement already satisfied: networkx in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.0.0->bert_score) (3.3)
Requirement already satisfied: jinja2 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.0.0->bert_score) (3.1.2)
Requirement already satisfied: fsspec in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.0.0->bert_score) (2024.6.1)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from torch>=1.0.0->bert_score) (2021.4.0)
Requirement already satisfied: colorama in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from tqdm>=4.31.1->bert_score) (0.4.6)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from transformers>=3.0.0->bert_score) (0.27.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from transformers>=3.0.0->bert_score) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from transformers>=3.0.0->bert_score) (2024.5.15)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from transformers>=3.0.0->bert_score) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from transformers>=3.0.0->bert_score) (0.4.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->bert_score) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->bert_score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->bert_score) (4.53.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->bert_score) (1.4.5)
Requirement already satisfied: pillow>=8 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->bert_score) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from matplotlib->bert_score) (3.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from requests->bert_score) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from requests->bert_score) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from requests->bert_score) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from requests->bert_score) (2023.11.17)
Requirement already satisfied: intel-openmp==2021.* in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=1.0.0->bert_score) (2021.4.0)
Requirement already satisfied: tbb==2021.* in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch>=1.0.0->bert_score) (2021.13.0)
Requirement already satisfied: six>=1.5 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert_score) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from jinja2->torch>=1.0.0->bert_score) (2.1.3)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in c:\users\22t312\appdata\local\programs\python\python311\lib\site-packages (from sympy->torch>=1.0.0->bert_score) (1.3.0)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
Installing collected packages: bert_score
Successfully installed bert_score-0.3.13
Note: you may need to restart the kernel to use updated packages.

In [39]:
refs = [
    "あいうえお", 
    "今日はいい天気ですね", 
    "今日は本当にいい天気",
    "暇な時間にはビデオゲームをするのが好きです。", 
    "太陽が空で輝いています。", 
    "今週末、海に旅行に行くつもりです。",
]
cands = [
    "夕食に食べるのは寿司が一番好きな食べ物です。", 
    "今日は良くない天気ですね",
    "今日は本当にいい天気", 
    "暇な時間にはビデオゲームをするのは楽しいです。", 
    "外では今、激しい雨が降っています。", 
    "週末は仕事で、楽しいことをすることができません。",
]

In [40]:
from bert_score import score
P, R, F1 = score(cands, refs, lang="ja")

In [19]:
import abc

class Tokenizer(abc.ABC):
  """Abstract base class for a tokenizer.

  Subclasses of Tokenizer must implement the tokenize() method.
  """

  @abc.abstractmethod
  def tokenize(self, text):
    raise NotImplementedError("Tokenizer must override tokenize() method")

In [21]:
from rouge_score import rouge_scorer
import MeCab  # MeCabを利用

# トークナイザークラス
class MeCabTokenizer(Tokenizer):
    def __init__(self, use_stemmer=False):
        self._stemmer = use_stemmer
        self.tagger = MeCab.Tagger()
        self.wakati = MeCab.Tagger("-Owakati")

    def tokenize(self, text):
        if self._stemmer:
            node = self.tagger.parseToNode(text)
            original_forms = []
            while node:
                feature = node.feature.split(",")
                original_forms.append(feature[6])  # 原型（lemma）
                node = node.next
            return original_forms
        else:
            return self.wakati.parse(text).split()

# トークナイザーを初期化
mecab_tokenizer = MeCabTokenizer()

# 日本語データ
target = "たかしが公園で遊んでいた。"
prediction = "たかしが公園にいたようだ。"

scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=False, tokenizer=mecab_tokenizer)
rouge_score = scorer.score(target, prediction)

# Rougeスコアの計算
rouge_score = scorer.score(target, prediction)

# 結果の表示
for metric, score in rouge_score.items():
    print(f"{metric}: Precision={score.precision:.4f}, Recall={score.recall:.4f}, F1={score.fmeasure:.4f}")

rouge1: Precision=0.7000, Recall=0.7000, F1=0.7000
rouge2: Precision=0.4444, Recall=0.4444, F1=0.4444
rougeL: Precision=0.7000, Recall=0.7000, F1=0.7000

### モデルの性能評価

In [33]:
# 保存済みモデルのディレクトリ
model_dir = "./results_ver2"
tokenizer = T5Tokenizer.from_pretrained(model_dir)
model = T5ForConditionalGeneration.from_pretrained(model_dir)

In [34]:
# T5モデルで要約を生成
def generate_summary(input_texts, model, tokenizer, max_length=128):
    summaries = []
    for text in input_texts:
        # トークナイズ
        inputs = tokenizer.encode("summarize: " + text, return_tensors="pt", truncation=True, max_length=1024)
        
        # 要約生成
        outputs = model.generate(inputs, max_length=max_length, min_length=10, length_penalty=2.0, num_beams=4, early_stopping=True)
        
        # デコード
        summary = tokenizer.decode(outputs[0], skip_special_tokens=True)
        summaries.append(summary)
    return summaries

In [3]:
# Rougeスコア
import abc
from rouge_score import rouge_scorer
import MeCab  

def calc_rougescore(reference, prediction, use_stemmer=False):
    class Tokenizer(abc.ABC):
    
      @abc.abstractmethod
      def tokenize(self, text):
        raise NotImplementedError("Tokenizer must override tokenize() method")
    
    class MeCabTokenizer(Tokenizer):
        def __init__(self, use_stemmer=False):
            self._stemmer = use_stemmer
            self.tagger = MeCab.Tagger()
            self.wakati = MeCab.Tagger("-Owakati")
    
        def tokenize(self, text):
            if self._stemmer:
                node = self.tagger.parseToNode(text)
                original_forms = []
                while node:
                    feature = node.feature.split(",")
                    original_forms.append(feature[6])  # 原型（lemma）
                    node = node.next
                return original_forms
            else:
                return self.wakati.parse(text).split()

    mecab_tokenizer = MeCabTokenizer()
    
    scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=False, tokenizer=mecab_tokenizer)
    rouge_score = scorer.score(reference, prediction)

    return rouge_score

In [4]:
# BERTScore
from bert_score import score

def calc_bertscore(reference, prediction, lang="ja"):
    P, R, F1 = score(reference, prediction, lang=lang, verbose=True)

    return F1

### 以下のコードはGPUを用いるため、Google colaboratryを利用する

In [ ]:
# 作成したモデルで要約を生成
summaries = generate_summary(X_test, model, tokenizer)

### 上記のコードからGoogle colaboratryで実施したテストデータを要約した文章を格納しているjsonファイルの読み込み

In [6]:
import json


with open("summaries.json", "r", encoding="utf-8") as file:
    summaries = json.load(file)

# データを表示
print(summaries[0], y_test[0])

<1>思わず「浮気をしたくなってしまう瞬間」を男性に聞いている<2>「元カノ」に再会してしまったとき、魅力的な女性と「お酒」を飲んだとき<3>魅力的な女性と「お酒」を飲んだときなど <S1>浮気をしたくなってしまう瞬間について、男性たちに聞いている<S2>彼女に「女」を感じなくなったとき、元カノに再会してしまったとき<S3>魅力的な女性とお酒を飲んだとき、寂しさを感じてしまったとき

### 自分で追加した特殊トークンを削除

In [15]:
modified_summaries = [summary.replace("<1>", "").replace("<2>", "").replace("<3>", "") for summary in summaries]

In [16]:
modified_y_test = [test.replace("<S1>", "").replace("<S2>","").replace("<S3>","") for test in y_test]

In [27]:
modified_summaries[8], modified_y_test[8]

('韓国発の辛いラーメン「辛ラーメン」に、世界初の公式「カレー辛ラーメン」が販売される唐辛子の辛さと牛肉エキス、50種類以上のスパイスがマッチした辛ラーメン反響がよければ商品化も検討されるという',
 'ニコニコ超会議2016では、公式の「カレー辛ラーメン」が登場する唐辛子の辛さと牛肉エキス、50種類以上のスパイスがマッチした辛ラーメンカレーとの相性もよく、反響がよければ商品化も検討されるという')

### 性能評価を行うコード

In [19]:


# Rougeスコアを格納するリスト
rouge_scores = {"rouge1": [], "rouge2": [], "rougeL": []}

# 各テストデータに対してRougeスコアを計算
for reference, prediction in zip(modified_y_test, modified_summaries):
    scores = calc_rougescore(reference, prediction)
    # それぞれF1値を求めるため.fmeasure(調和平均)を用いる
    rouge_scores["rouge1"].append(scores["rouge1"].fmeasure)
    rouge_scores["rouge2"].append(scores["rouge2"].fmeasure)
    rouge_scores["rougeL"].append(scores["rougeL"].fmeasure)

# Rougeスコアの平均値を計算
average_scores = {}
for metric, values in scores.items():
    average_scores[metric] = np.mean(values)

print(f"Rouge値の平均値 {average_scores}")

# BERTScoreを計算
bert_F1_scores = calc_bertscore(modified_y_test, modified_summaries, lang="ja")
# BERTScoreの平均値を計算
avg_bert_F1 = bert_F1_scores.mean().item()
print(f"BERTSCcoreのF1値の平均値: {avg_bert_F1:.4f}")

Rouge値の平均値 {'rouge1': 0.6556923918992884, 'rouge2': 0.43895691977761553, 'rougeL': 0.46588669950738915}
calculating scores...
computing bert embedding.

  0%|          | 0/44 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/22 [00:00<?, ?it/s]

done in 777.88 seconds, 1.81 sentences/sec
BERTSCcoreのF1値の平均値: 0.7422

**memo**
- f1値がそれぞれ出力された

### 実際にシステムに使用する要約文を作成

In [4]:
from transformers import T5Tokenizer, T5ForConditionalGeneration
import pandas as pd

# 保存済みモデルのディレクトリ
model_dir = "./results_ver2"
tokenizer = T5Tokenizer.from_pretrained(model_dir)
model = T5ForConditionalGeneration.from_pretrained(model_dir)

# CSVファイルを読み込み
df = pd.read_csv('../ニュースサイト関連/news.csv')
week_df = df[df['日付'] == '2025-01-20']

input_text = week_df['本文']
input_text = list(input_text)

# 要約結果を保存するリスト
# summaries = []

# 各ニュース本文を処理
for text in input_text[5:]:
    # トークナイズ(モデルが認識できるように文字データを数値データに変換させる)
    inputs = tokenizer(
        "summarize: " + text,
        return_tensors="pt",
        max_length=1024,
        truncation=True,
        padding=True
    )

    # 要約生成
    summary_ids = model.generate(
        inputs["input_ids"],
        max_length=128,
        num_beams=4,    # 4つの候補から最適な出力を選択
        early_stopping=True
    )

    # 要約結果を取得
    # 数値データ　→　文字データ
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
    summaries.append(summary)

print(summaries)

['<1>ウクライナが公開した北朝鮮兵士2人の映像を紹介している<2>「実戦訓練に行くと言われた」北朝鮮兵は、ロシア軍の身分証明書を持っていましたが別人の名前でした<3>「実戦訓練に行くと言われた」とだまされ、最前線に送られたという', '<1>大谷翔平選手がホームラン50本、盗塁50の「5050」を達成したときのボールを、台湾企業が日本に売却する意向があることが分かりました<2>Cキャピタルは「ボールが日本に帰るのは良いこと」との考えを持っていて売却の意向があるとのこと', '<1>天童よしみが「昭和100年ボウリングの集い」を開催した<2>近所の方が集まって一緒に歌を歌ったり、すごく楽しい過ごし方をしていたと振り返った<3>「すごく楽しい過ごし方をしていて、とても温かかった」と振り返った', '<1>福島県郡山市を走る東北新幹線から突如、火花が上がった<2>突然、激しい破裂音とともに走行する新幹線の上が明るく光った<3>突然、激しい破裂音とともに走行する新幹線の上が明るく光ったという', '<1>日本生命がフジテレビで放送しているCを当面の間、差し替えることが分かりました<2>中居正広さんと女性とのトラブルにフジテレビの社員が関与していたと一部週刊誌が報じたことを受けたもの<3>20日以降の「めざましテレビ」のCについても今後、差し替える方針だという', '<1>新卒の初任給を30万円に引き上げる企業が次々と出てくる中、就職氷河期世代からは嘆きの声が上がっている<2>新卒の初任給を30万円に引き上げる企業が次々と出てくる中、就職氷河期世代からは嘆きの声が上がっているという', '<1>フジテレビは16日、中居正広の女性トラブルなど一連の報道について、港浩一社長らが定例会見で説明する方針だと報じました<2>週刊誌の報道についても説明するとみられ、週刊誌の報道についても説明するという', '<1>三井住友銀行は12日午後6時から13日の正午まで各サービスを休止した<2>新システムへの移行のためで、やインターネットバンキングの他に各種サービスが利用できなくなる<3>事前に周知されていたが、知らなかったという人もいた', '<1>能登半島地震から1年を迎え、地震調査委員会の委員長は地震活動について強い揺れへの注意を呼び掛ける見解を発表した<2>地震調査委員会の委員長は、これまでの地震活動は「経験したことのない現象」として、引き続き強い揺れへの注意を呼び掛ける見解を発表した', '<1>帝国データバンクによると、去年1年間のコメ農家の倒産・廃業件数は42件でした<2>前年の年から2割増加し、年間の最多件数を更新した<3>トラクターなどの機材調達費が捻出できないことや後継者不足がコメ農家の廃業を後押ししている']

In [ ]:
df

In [ ]:
# データフレームに要約を追加
df['モデル要約'] = summaries

# 結果を保存
df.to_csv("news.csv", index=False, encording='utf-8-sig')